### ISSUE TITLE
[Implementation] ABSTRACT's showing up in MOVIZ

### ISSUE THREAD

**Issue by Free-Quarks** [ml4ai/moviz-client#5]
1 or 2 gromet versions ago (somewhat recently) there was a new type of box added called `"ABSTRACT"`  . These are essentially the exact same as primitives but have a different name because the primitive operation they perform is "under the hood". They are mostly for unpacking and packing tuples in python. @titomeister 

I noticed they aren't being created in the visuals, which I'm guessing is because we forgot to tell you about them during that gromet version update, sorry about that.

**Comment by hconhisway** [comment]
Support for abstract is now added.
